[tool.black]
line-length = 100
target-version = ["py312"]

[tool.ruff]
line-length = 100
target-version = "py312"
respect-gitignore = true

[tool.ruff.lint]
select = [
  "E",   # pycodestyle errors
  "F",   # pyflakes
  "I",   # isort
  "B",   # flake8-bugbear
  "UP",  # pyupgrade
  "SIM", # flake8-simplify
]
ignore = [
  "E501",  # line length handled by formatter
]

[tool.ruff.format]
quote-style = "preserve"
indent-style = "space"

[tool.mypy]
python_version = "3.12"
plugins = []
show_error_codes = true
pretty = true
warn_unused_ignores = true
warn_redundant_casts = true
warn_unreachable = true
no_implicit_optional = true
check_untyped_defs = true
ignore_missing_imports = true
exclude = [
  "migrations/",
  "tests/",
]

[[tool.mypy.overrides]]
module = ["app.*"]
disallow_untyped_defs = false
disallow_any_generics = false


[tool.ruff.lint.per-file-ignores]
"app/routers/web.py" = ["B008", "UP045", "I001", "UP006", "UP035"]
"app/security/__init__.py" = ["I001"]
"app/security/csrf.py" = ["I001"]
"app/store_db.py" = ["I001", "UP035", "UP006", "UP045"]
"migrations/env.py" = ["I001", "F401"]
"migrations/versions/*.py" = ["I001", "UP007", "UP035"]
"tests/conftest.py" = ["E401", "I001", "E402", "SIM115"]
"tests/*.py" = ["UP035", "UP006", "B007"]

"app/routers/tasks.py" = ["B008"]
"app/routers/auth.py" = ["B008"]
"app/main.py" = ["E402", "F401", "I001"]

"app/auth.py" = ["B008"]
