name: CI

on:
  push:
  pull_request:

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Lint (ruff) and format check (black)
        run: |
          ruff check --fix .
          black .

      - name: Type check (mypy)
        run: mypy .

      - name: Run tests (pytest)
        env:
          PYTHONPATH: .
        run: pytest -q

